name: Docker Compose Validation

on:
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate docker-compose.piholedoh.yml
        run: docker compose -f docker-compose.piholedoh.yml config

      - name: Validate docker-compose.traefik.yml
        run: docker compose -f docker-compose.traefik.yml config
